// import 'package:get/get.dart';
// import 'package:upcpro_app/Models/nivel.dart';
// import 'package:upcpro_app/Models/pregunta.dart';

// class ControllerNiveles extends GetxController {
//   // final Rxn<Usuario> _user = Rxn<Usuario>();
//   // Usuario? get user => _user.value;

//   // Future<void> DataUser(Usuario user) async {
//   //   _user.value = user;
//   // }

//   final Rxn<String> _competenciaSeledted = Rxn<String>();
//   String? get competenciaSeledted => _competenciaSeledted.value;

//   //niveles
//   final Rxn<List<Nivel>> _niveles = Rxn<List<Nivel>>();
//   List<Nivel>? get niveles => _niveles.value;

//   Future<void> selectedCompetencia(String competencia) async {
//     _competenciaSeledted.value = competencia;

//     _niveles.value = [];

//     if (competencia == "Inglés") {

//       _niveles.value = [
//         Nivel(
//             nivel: 1,
//             preguntas: [
//               Pregunta(
//                   encabezado: "",
//                   question: "People often cry when they feel like this.",
//                   imagenEncabezado: "",
//                   opcionA: "sad",
//                   opcionB: "hungry",
//                   opcionC: "cold",
//                   opcionD: "afraid",
//                   opcionCorrecta: 1,
//                   retroalimentacion: "sad",
//                   tipoCompetencia: 4,
//                   complejidad: 2,
//                   tipoPregunta: 1,
//                   id: 1)
//             ],
//             dificultad: 1,
//             id: 1),
//       ];
//       return;
//     }

//     if (competencia == "Razonamiento Cuantitativo") {
//       _niveles.value = [];
//       return;
//     }

//     if (competencia == "Lectura Crítica") {
//       _niveles.value = [];
//       return;
//     }

//     if (competencia == "Competencias Ciudadanas") {
//       _niveles.value = [];
//       return;
//     }
//   }
// }

import 'package:get/get.dart';
import 'package:upcpro_app/Models/nivel.dart';
import 'package:upcpro_app/Models/pregunta.dart';

class ControllerNiveles extends GetxController {
  final niveles = <Nivel>[
    // Razonamiento Cuantitativo
    Nivel(
      competencia: 1,
      nivel: 1,
      preguntas: [
        Pregunta(
            encabezado: "",
            question:
                "Si un carro viaja 60 km en 1 hora, ¿cuánto viajará en 2.5 horas?",
            imagenEncabezado: "",
            opcionA: "120 km",
            opcionB: "150 km",
            opcionC: "180 km",
            opcionD: "200 km",
            opcionCorrecta: 2,
            retroalimentacion: " 60 km/h * 2.5 h = 150 km.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 1),
        Pregunta(
            encabezado: "",
            question: "¿Qué es el 25% de 200?",
            imagenEncabezado: "",
            opcionA: "25",
            opcionB: "50",
            opcionC: "75",
            opcionD: "100",
            opcionCorrecta: 2,
            retroalimentacion: " El 25% de 200 es 50.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 2),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene una longitud de 10 cm y un ancho de 5 cm, ¿cuál es su área?",
            imagenEncabezado: "",
            opcionA: "15 cm²",
            opcionB: "50 cm²",
            opcionC: "100 cm²",
            opcionD: "25 cm²",
            opcionCorrecta: 2,
            retroalimentacion:
                " Área = longitud * ancho = 10 cm * 5 cm = 50 cm².",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 3),
      ],
      dificultad: 1,
      id: 1,
    ),
    Nivel(
      competencia: 1,
      nivel: 2,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 15 * 4?",
            imagenEncabezado: "",
            opcionA: "60",
            opcionB: "50",
            opcionC: "70",
            opcionD: "80",
            opcionCorrecta: 1,
            retroalimentacion: " 15 * 4 = 60.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 4),
        Pregunta(
            encabezado: "",
            question:
                "Si un tren sale a las 3:00 PM y viaja 2 horas y 30 minutos, ¿a qué hora llega?",
            imagenEncabezado: "",
            opcionA: "5:30 PM",
            opcionB: "6:00 PM",
            opcionC: "6:30 PM",
            opcionD: "7:00 PM",
            opcionCorrecta: 1,
            retroalimentacion:
                " Sale a las 3:00 PM y viaja 2 horas y 30 minutos, llega a las 5:30 PM.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 5),
        Pregunta(
            encabezado: "",
            question: "¿Qué número es mayor: 3/4 o 2/3?",
            imagenEncabezado: "",
            opcionA: "3/4",
            opcionB: "2/3",
            opcionC: "Son iguales",
            opcionD: "No se puede determinar",
            opcionCorrecta: 1,
            retroalimentacion: " 3/4 es mayor que 2/3.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 6),
      ],
      dificultad: 1,
      id: 2,
    ),
    Nivel(
      competencia: 1,
      nivel: 3,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 9 + 6 * 2?",
            imagenEncabezado: "",
            opcionA: "21",
            opcionB: "18",
            opcionC: "15",
            opcionD: " 12",
            opcionCorrecta: 1,
            retroalimentacion: " 6 * 2 = 12, y 9 + 12 = 21.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 7),
        Pregunta(
            encabezado: "",
            question:
                "Si un triángulo tiene una base de 8 cm y una altura de 5 cm, ¿cuál es su área?",
            imagenEncabezado: "",
            opcionA: "20 cm²",
            opcionB: "30 cm²",
            opcionC: "40 cm²",
            opcionD: "50 cm²",
            opcionCorrecta: 1,
            retroalimentacion:
                " Área = (base * altura) / 2 = (8 cm * 5 cm) / 2 = 20 cm².",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 8),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 100 dividido entre 4?",
            imagenEncabezado: "",
            opcionA: "20",
            opcionB: "25",
            opcionC: "30",
            opcionD: "35",
            opcionCorrecta: 2,
            retroalimentacion: " 100 / 4 = 25.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 9),
      ],
      dificultad: 1,
      id: 3,
    ),
    // Continúa creando los niveles de Razonamiento Cuantitativo hasta el nivel 20...
    Nivel(
      competencia: 1,
      nivel: 4,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 12 * 3?",
            imagenEncabezado: "",
            opcionA: "36",
            opcionB: "30",
            opcionC: "24",
            opcionD: "18",
            opcionCorrecta: 1,
            retroalimentacion: " 12 * 3 = 36.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 10),
        Pregunta(
            encabezado: "",
            question:
                "Si un coche consume 8 litros de gasolina cada 100 km, ¿cuántos litros necesitará para recorrer 250 km?",
            imagenEncabezado: "",
            opcionA: "12 litros",
            opcionB: "16 litros",
            opcionC: "20 litros",
            opcionD: "22 litros",
            opcionCorrecta: 2,
            retroalimentacion:
                " 250 km / 100 km * 8 litros = 20 litros.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 11),
        Pregunta(
            encabezado: "",
            question: "¿Cuál es el resultado de 15 - 7 + 3?",
            imagenEncabezado: "",
            opcionA: "11",
            opcionB: "10",
            opcionC: "9",
            opcionD: "8",
            opcionCorrecta: 1,
            retroalimentacion: " 15 - 7 + 3 = 11.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 12),
      ],
      dificultad: 1,
      id: 4,
    ),
    Nivel(
      competencia: 1,
      nivel: 5,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 5²?",
            imagenEncabezado: "",
            opcionA: "10",
            opcionB: "20",
            opcionC: "25",
            opcionD: "30",
            opcionCorrecta: 3,
            retroalimentacion: " 5² = 25.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 13),
        Pregunta(
            encabezado: "",
            question:
                "Si un círculo tiene un radio de 7 cm, ¿cuál es su perímetro? (Usa π ≈ 3.14)",
            imagenEncabezado: "",
            opcionA: "21.98 cm",
            opcionB: "43.96 cm",
            opcionC: "49.00 cm",
            opcionD: "50.24 cm",
            opcionCorrecta: 2,
            retroalimentacion:
                " Perímetro = 2 * π * radio = 2 * 3.14 * 7 cm ≈ 43.96 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 14),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 8 * (2 + 2)?",
            imagenEncabezado: "",
            opcionA: "32",
            opcionB: "24",
            opcionC: "16",
            opcionD: "20",
            opcionCorrecta: 1,
            retroalimentacion: " 8 * (2 + 2) = 8 * 4 = 32.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 15),
      ],
      dificultad: 1,
      id: 5,
    ),
    Nivel(
      competencia: 1,
      nivel: 6,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 18 / 3?",
            imagenEncabezado: "",
            opcionA: "6",
            opcionB: "5",
            opcionC: "4",
            opcionD: "3",
            opcionCorrecta: 1,
            retroalimentacion: " 18 / 3 = 6.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 16),
        Pregunta(
            encabezado: "",
            question:
                "Si un triángulo tiene lados de 3 cm, 4 cm y 5 cm, ¿es un triángulo rectángulo?",
            imagenEncabezado: "",
            opcionA: "Sí",
            opcionB: "No",
            opcionC: "No se puede determinar",
            opcionD: "Depende de los ángulos",
            opcionCorrecta: 1,
            retroalimentacion:
                " 3² + 4² = 5², por lo tanto es un triángulo rectángulo.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 17),
        Pregunta(
            encabezado: "",
            question: "¿Cuál es el resultado de 7 + 3 * 2?",
            imagenEncabezado: "",
            opcionA: "13",
            opcionB: "16",
            opcionC: "10",
            opcionD: "12",
            opcionCorrecta: 1,
            retroalimentacion: " 3 * 2 = 6, y 7 + 6 = 13.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 18),
      ],
      dificultad: 1,
      id: 6,
    ),
    Nivel(
      competencia: 1,
      nivel: 7,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 14 - 5 + 2?",
            imagenEncabezado: "",
            opcionA: "11",
            opcionB: "10",
            opcionC: "9",
            opcionD: "8",
            opcionCorrecta: 1,
            retroalimentacion: " 14 - 5 + 2 = 11.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 19),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene un perímetro de 30 cm y una longitud de 10 cm, ¿cuál es su ancho?",
            imagenEncabezado: "",
            opcionA: "5 cm",
            opcionB: "10 cm",
            opcionC: "7.5 cm",
            opcionD: "15 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Perímetro = 2 * (longitud + ancho), 30 = 2 * (10 + ancho) => ancho = 5 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 20),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 3 * 3 * 3?",
            imagenEncabezado: "",
            opcionA: "27",
            opcionB: "9",
            opcionC: "6",
            opcionD: "12",
            opcionCorrecta: 1,
            retroalimentacion: " 3 * 3 * 3 = 27.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 21),
      ],
      dificultad: 1,
      id: 7,
    ),
    Nivel(
      competencia: 1,
      nivel: 8,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 20 - 4 * 3?",
            imagenEncabezado: "",
            opcionA: "8",
            opcionB: "12",
            opcionC: "16",
            opcionD: "20",
            opcionCorrecta: 2,
            retroalimentacion: " 4 * 3 = 12, y 20 - 12 = 8.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 22),
        Pregunta(
            encabezado: "",
            question:
                "Si un cuadrado tiene un área de 64 cm², ¿cuál es la longitud de uno de sus lados?",
            imagenEncabezado: "",
            opcionA: "6 cm",
            opcionB: "8 cm",
            opcionC: "10 cm",
            opcionD: "12 cm",
            opcionCorrecta: 2,
            retroalimentacion:
                " Área = lado * lado, 64 = lado² => lado = 8 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 23),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 45 + 55?",
            imagenEncabezado: "",
            opcionA: "90",
            opcionB: "100",
            opcionC: "110",
            opcionD: "120",
            opcionCorrecta: 1,
            retroalimentacion: " 45 + 55 = 100.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 24),
      ],
      dificultad: 1,
      id: 8,
    ),
    Nivel(
      competencia: 1,
      nivel: 9,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 100 - 25 * 2?",
            imagenEncabezado: "",
            opcionA: "50",
            opcionB: "75",
            opcionC: "80",
            opcionD: "70",
            opcionCorrecta: 2,
            retroalimentacion: " 25 * 2 = 50, y 100 - 50 = 50.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 25),
        Pregunta(
            encabezado: "",
            question:
                "Si un triángulo tiene un área de 30 cm² y una base de 10 cm, ¿cuál es su altura?",
            imagenEncabezado: "",
            opcionA: "6 cm",
            opcionB: "5 cm",
            opcionC: "4 cm",
            opcionD: "3 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Área = (base * altura) / 2 => 30 = (10 * altura) / 2 => altura = 6 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 26),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 8 * 7?",
            imagenEncabezado: "",
            opcionA: "54",
            opcionB: "56",
            opcionC: "58",
            opcionD: "60",
            opcionCorrecta: 2,
            retroalimentacion: " 8 * 7 = 56.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 27),
      ],
      dificultad: 1,
      id: 9,
    ),
    Nivel(
      competencia: 1,
      nivel: 10,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 3 * (4 + 5)?",
            imagenEncabezado: "",
            opcionA: "27",
            opcionB: "27",
            opcionC: "27",
            opcionD: "27",
            opcionCorrecta: 1,
            retroalimentacion: " 3 * (4 + 5) = 3 * 9 = 27.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 28),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene un área de 50 cm² y una longitud de 10 cm, ¿cuál es su ancho?",
            imagenEncabezado: "",
            opcionA: "5 cm",
            opcionB: "10 cm",
            opcionC: "15 cm",
            opcionD: "20 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Área = longitud * ancho, 50 = 10 * ancho => ancho = 5 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 29),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 2³?",
            imagenEncabezado: "",
            opcionA: "4",
            opcionB: "6",
            opcionC: "8",
            opcionD: "10",
            opcionCorrecta: 3,
            retroalimentacion: " 2³ = 8.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 30),
      ],
      dificultad: 1,
      id: 10,
    ),
    Nivel(
      competencia: 1,
      nivel: 11,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 5 + 5 * 2?",
            imagenEncabezado: "",
            opcionA: "15",
            opcionB: "10",
            opcionC: "20",
            opcionD: "25",
            opcionCorrecta: 2,
            retroalimentacion: " 5 + 5 * 2 = 5 + 10 = 15.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 31),
        Pregunta(
            encabezado: "",
            question:
                "Si un coche viaja a 80 km/h, ¿cuánto tardará en recorrer 160 km?",
            imagenEncabezado: "",
            opcionA: "1 hora",
            opcionB: "2 horas",
            opcionC: "3 horas",
            opcionD: "4 horas",
            opcionCorrecta: 2,
            retroalimentacion:
                " Tiempo = distancia / velocidad = 160 km / 80 km/h = 2 horas.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 32),
        Pregunta(
            encabezado: "",
            question: "¿Cuál es el resultado de 10 * 10 - 5?",
            imagenEncabezado: "",
            opcionA: "95",
            opcionB: "100",
            opcionC: "105",
            opcionD: "110",
            opcionCorrecta: 1,
            retroalimentacion: " 10 * 10 - 5 = 100 - 5 = 95.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 33),
      ],
      dificultad: 1,
      id: 11,
    ),
    Nivel(
      competencia: 1,
      nivel: 12,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 6 * 6?",
            imagenEncabezado: "",
            opcionA: "30",
            opcionB: "36",
            opcionC: "42",
            opcionD: "48",
            opcionCorrecta: 2,
            retroalimentacion: " 6 * 6 = 36.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 34),
        Pregunta(
            encabezado: "",
            question:
                "Si un tren sale a las 2:00 PM y viaja 3 horas, ¿a qué hora llega?",
            imagenEncabezado: "",
            opcionA: "4:00 PM",
            opcionB: "5:00 PM",
            opcionC: "6:00 PM",
            opcionD: "7:00 PM",
            opcionCorrecta: 2,
            retroalimentacion:
                " Sale a las 2:00 PM y viaja 3 horas, llega a las 5:00 PM.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 35),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 50 / 5?",
            imagenEncabezado: "",
            opcionA: "5",
            opcionB: "10",
            opcionC: "15",
            opcionD: "20",
            opcionCorrecta: 2,
            retroalimentacion: " 50 / 5 = 10.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 36),
      ],
      dificultad: 1,
      id: 12,
    ),
    Nivel(
      competencia: 1,
      nivel: 13,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 7 * 8?",
            imagenEncabezado: "",
            opcionA: "54",
            opcionB: "56",
            opcionC: "58",
            opcionD: "60",
            opcionCorrecta: 2,
            retroalimentacion: " 7 * 8 = 56.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 37),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene un área de 36 cm² y un ancho de 6 cm, ¿cuál es su longitud?",
            imagenEncabezado: "",
            opcionA: "4 cm",
            opcionB: "6 cm",
            opcionC: "8 cm",
            opcionD: "10 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Área = longitud * ancho, 36 = longitud * 6 => longitud = 6 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 38),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 9 - 3 + 2?",
            imagenEncabezado: "",
            opcionA: "8",
            opcionB: "7",
            opcionC: "6",
            opcionD: "5",
            opcionCorrecta: 1,
            retroalimentacion: " 9 - 3 + 2 = 8.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 39),
      ],
      dificultad: 1,
      id: 13,
    ),
    Nivel(
      competencia: 1,
      nivel: 14,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 4 * 5?",
            imagenEncabezado: "",
            opcionA: "20",
            opcionB: "25",
            opcionC: "30",
            opcionD: "35",
            opcionCorrecta: 1,
            retroalimentacion: " 4 * 5 = 20.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 40),
        Pregunta(
            encabezado: "",
            question:
                "Si un coche viaja a 60 km/h, ¿cuánto tardará en recorrer 120 km?",
            imagenEncabezado: "",
            opcionA: "1 hora",
            opcionB: "2 horas",
            opcionC: "3 horas",
            opcionD: "4 horas",
            opcionCorrecta: 2,
            retroalimentacion:
                " Tiempo = distancia / velocidad = 120 km / 60 km/h = 2 horas.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 41),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 15 + 15?",
            imagenEncabezado: "",
            opcionA: "25",
            opcionB: "30",
            opcionC: "20",
            opcionD: "15",
            opcionCorrecta: 2,
            retroalimentacion: " 15 + 15 = 30.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 42),
      ],
      dificultad: 1,
      id: 14,
    ),
    Nivel(
      competencia: 1,
      nivel: 15,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 10 * 10?",
            imagenEncabezado: "",
            opcionA: "90",
            opcionB: "100",
            opcionC: "110",
            opcionD: "120",
            opcionCorrecta: 2,
            retroalimentacion: " 10 * 10 = 100.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 43),
        Pregunta(
            encabezado: "",
            question:
                "Si un tren sale a las 4:00 PM y viaja 2 horas y 15 minutos, ¿a qué hora llega?",
            imagenEncabezado: "",
            opcionA: "5:15 PM",
            opcionB: "6:15 PM",
            opcionC: "6:30 PM",
            opcionD: "7:00 PM",
            opcionCorrecta: 2,
            retroalimentacion:
                " Sale a las 4:00 PM y viaja 2 horas y 15 minutos, llega a las 6:15 PM.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 44),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 30 / 5?",
            imagenEncabezado: "",
            opcionA: "5",
            opcionB: "6",
            opcionC: "7",
            opcionD: "8",
            opcionCorrecta: 2,
            retroalimentacion: " 30 / 5 = 6.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 45),
      ],
      dificultad: 1,
      id: 15,
    ),
    Nivel(
      competencia: 1,
      nivel: 16,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 8 * 8?",
            imagenEncabezado: "",
            opcionA: "64",
            opcionB: "72",
            opcionC: "80",
            opcionD: "88",
            opcionCorrecta: 1,
            retroalimentacion: " 8 * 8 = 64.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 46),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene un área de 48 cm² y un ancho de 6 cm, ¿cuál es su longitud?",
            imagenEncabezado: "",
            opcionA: "6 cm",
            opcionB: "8 cm",
            opcionC: "10 cm",
            opcionD: "12 cm",
            opcionCorrecta: 2,
            retroalimentacion:
                " Área = longitud * ancho, 48 = longitud * 6 => longitud = 8 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 47),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 20 - 5 + 10?",
            imagenEncabezado: "",
            opcionA: "25",
            opcionB: "20",
            opcionC: "15",
            opcionD: "30",
            opcionCorrecta: 1,
            retroalimentacion: " 20 - 5 + 10 = 25.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 48),
      ],
      dificultad: 1,
      id: 16,
    ),
    Nivel(
      competencia: 1,
      nivel: 17,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 5 * 5?",
            imagenEncabezado: "",
            opcionA: "20",
            opcionB: "25",
            opcionC: "30",
            opcionD: "35",
            opcionCorrecta: 2,
            retroalimentacion: " 5 * 5 = 25.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 49),
        Pregunta(
            encabezado: "",
            question:
                "Si un coche viaja a 90 km/h, ¿cuánto tardará en recorrer 180 km?",
            imagenEncabezado: "",
            opcionA: "1 hora",
            opcionB: "2 horas",
            opcionC: "3 horas",
            opcionD: "4 horas",
            opcionCorrecta: 2,
            retroalimentacion:
                " Tiempo = distancia / velocidad = 180 km / 90 km/h = 2 horas.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 50),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 100 - 20 / 4?",
            imagenEncabezado: "",
            opcionA: "95",
            opcionB: "90",
            opcionC: "85",
            opcionD: "80",
            opcionCorrecta: 1,
            retroalimentacion: " 20 / 4 = 5, y 100 - 5 = 95.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 51),
      ],
      dificultad: 1,
      id: 17,
    ),
    Nivel(
      competencia: 1,
      nivel: 18,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 3 * 3 * 3?",
            imagenEncabezado: "",
            opcionA: "27",
            opcionB: "30",
            opcionC: "24",
            opcionD: "21",
            opcionCorrecta: 1,
            retroalimentacion: " 3 * 3 * 3 = 27.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 52),
        Pregunta(
            encabezado: "",
            question:
                "Si un cuadrado tiene un área de 36 cm², ¿cuál es la longitud de uno de sus lados?",
            imagenEncabezado: "",
            opcionA: "6 cm",
            opcionB: "8 cm",
            opcionC: "10 cm",
            opcionD: "12 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Área = lado * lado, 36 = lado² => lado = 6 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 53),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 50 + 25?",
            imagenEncabezado: "",
            opcionA: "70",
            opcionB: "75",
            opcionC: "80",
            opcionD: "85",
            opcionCorrecta: 2,
            retroalimentacion: " 50 + 25 = 75.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 54),
      ],
      dificultad: 1,
      id: 18,
    ),
    Nivel(
      competencia: 1,
      nivel: 19,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 8 * 7?",
            imagenEncabezado: "",
            opcionA: "54",
            opcionB: "56",
            opcionC: "58",
            opcionD: "60",
            opcionCorrecta: 2,
            retroalimentacion: " 8 * 7 = 56.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 55),
        Pregunta(
            encabezado: "",
            question:
                "Si un rectángulo tiene un perímetro de 40 cm y una longitud de 12 cm, ¿cuál es su ancho?",
            imagenEncabezado: "",
            opcionA: "8 cm",
            opcionB: "10 cm",
            opcionC: "12 cm",
            opcionD: "14 cm",
            opcionCorrecta: 1,
            retroalimentacion:
                " Perímetro = 2 * (longitud + ancho), 40 = 2 * (12 + ancho) => ancho = 8 cm.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 56),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 100 + 200?",
            imagenEncabezado: "",
            opcionA: "300",
            opcionB: "400",
            opcionC: "500",
            opcionD: "600",
            opcionCorrecta: 1,
            retroalimentacion: " 100 + 200 = 300.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 57),
      ],
      dificultad: 1,
      id: 19,
    ),
    Nivel(
      competencia: 1,
      nivel: 20,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 15 * 4?",
            imagenEncabezado: "",
            opcionA: "60",
            opcionB: "50",
            opcionC: "70",
            opcionD: "80",
            opcionCorrecta: 1,
            retroalimentacion: " 15 * 4 = 60.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 58),
        Pregunta(
            encabezado: "",
            question:
                "Si un coche viaja a 90 km/h, ¿cuánto tardará en recorrer 270 km?",
            imagenEncabezado: "",
            opcionA: "2 horas",
            opcionB: "3 horas",
            opcionC: "4 horas",
            opcionD: "5 horas",
            opcionCorrecta: 2,
            retroalimentacion:
                " Tiempo = distancia / velocidad = 270 km / 90 km/h = 3 horas.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 59),
        Pregunta(
            encabezado: "",
            question: "¿Cuánto es 12 + 8?",
            imagenEncabezado: "",
            opcionA: "18",
            opcionB: "20",
            opcionC: "22",
            opcionD: "24",
            opcionCorrecta: 2,
            retroalimentacion: " 12 + 8 = 20.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 60),
      ],
      dificultad: 1,
      id: 20,
    ),
    // Inglés
    Nivel(
      competencia: 2,
      nivel: 1,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'hot'?",
            imagenEncabezado: "",
            opcionA: "Cold",
            opcionB: "Warm",
            opcionC: "Cool",
            opcionD: "Boiling",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'hot' is 'cold'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 61),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a verb?",
            imagenEncabezado: "",
            opcionA: "Quick",
            opcionB: "Run",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Run' is a verb.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 62),
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'child'?",
            imagenEncabezado: "",
            opcionA: "Childs",
            opcionB: "Children",
            opcionC: "Childes",
            opcionD: "Childer",
            opcionCorrecta: 2,
            retroalimentacion:
                " The plural of 'child' is 'children'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 63),
      ],
      dificultad: 1,
      id: 3,
    ),
    Nivel(
      competencia: 2,
      nivel: 2,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'eat'?",
            imagenEncabezado: "",
            opcionA: "Eaten",
            opcionB: "Ate",
            opcionC: "Eating",
            opcionD: "Eats",
            opcionCorrecta: 2,
            retroalimentacion: " The past tense of 'eat' is 'ate'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 64),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a noun?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Happiness",
            opcionC: "Running",
            opcionD: "Beautiful",
            opcionCorrecta: 2,
            retroalimentacion: " 'Happiness' is a noun.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 65),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'fast'?",
            imagenEncabezado: "",
            opcionA: "Quick",
            opcionB: "Slow",
            opcionC: "Steady",
            opcionD: "Lazy",
            opcionCorrecta: 1,
            retroalimentacion: " 'Quick' is a synonym of 'fast'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 66),
      ],
      dificultad: 1,
      id: 4,
    ),
    Nivel(
      competencia: 2,
      nivel: 3,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'happy'?",
            imagenEncabezado: "",
            opcionA: "Sad",
            opcionB: "Joyful",
            opcionC: "Excited",
            opcionD: "Angry",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'happy' is 'sad'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 67),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a preposition?",
            imagenEncabezado: "",
            opcionA: "Under",
            opcionB: "Run",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Under' is a preposition.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 68),
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'go'?",
            imagenEncabezado: "",
            opcionA: "Goes",
            opcionB: "Gone",
            opcionC: "Went",
            opcionD: "Going",
            opcionCorrecta: 3,
            retroalimentacion: " The past tense of 'go' is 'went'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 69),
      ],
      dificultad: 1,
      id: 5,
    ),
    Nivel(
      competencia: 2,
      nivel: 4,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'mouse'?",
            imagenEncabezado: "",
            opcionA: "Mouses",
            opcionB: "Mice",
            opcionC: "Mouses",
            opcionD: "Mices",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'mouse' is 'mice'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 70),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adjective?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Beautiful' is an adjective.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 71),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'big'?",
            imagenEncabezado: "",
            opcionA: "Large",
            opcionB: "Small",
            opcionC: "Huge",
            opcionD: "Tall",
            opcionCorrecta: 2,
            retroalimentacion: " The opposite of 'big' is 'small'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 72),
      ],
      dificultad: 1,
      id: 6,
    ),
    Nivel(
      competencia: 2,
      nivel: 5,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'sing'?",
            imagenEncabezado: "",
            opcionA: "Sang",
            opcionB: "Sung",
            opcionC: "Singing",
            opcionD: "Sings",
            opcionCorrecta: 1,
            retroalimentacion: " The past tense of 'sing' is 'sang'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 73),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a conjunction?",
            imagenEncabezado: "",
            opcionA: "And",
            opcionB: "Quick",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'And' is a conjunction.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 74),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'happy'?",
            imagenEncabezado: "",
            opcionA: "Sad",
            opcionB: "Joyful",
            opcionC: "Angry",
            opcionD: "Tired",
            opcionCorrecta: 2,
            retroalimentacion: " 'Joyful' is a synonym of 'happy'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 75),
      ],
      dificultad: 1,
      id: 7,
    ),
    Nivel(
      competencia: 2,
      nivel: 6,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'tooth'?",
            imagenEncabezado: "",
            opcionA: "Tooths",
            opcionB: "Teeth",
            opcionC: "Tooths",
            opcionD: "Teeths",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'tooth' is 'teeth'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 76),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adverb?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Quickly' is an adverb.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 77),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'light'?",
            imagenEncabezado: "",
            opcionA: "Bright",
            opcionB: "Heavy",
            opcionC: "Dark",
            opcionD: "Clear",
            opcionCorrecta: 3,
            retroalimentacion: " The opposite of 'light' is 'dark'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 78),
      ],
      dificultad: 1,
      id: 8,
    ),
    Nivel(
      competencia: 2,
      nivel: 7,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'write'?",
            imagenEncabezado: "",
            opcionA: "Wrote",
            opcionB: "Written",
            opcionC: "Writing",
            opcionD: "Writes",
            opcionCorrecta: 1,
            retroalimentacion:
                " The past tense of 'write' is 'wrote'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 79),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a preposition?",
            imagenEncabezado: "",
            opcionA: "Under",
            opcionB: "Run",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Under' is a preposition.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 80),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'angry'?",
            imagenEncabezado: "",
            opcionA: "Happy",
            opcionB: "Mad",
            opcionC: "Excited",
            opcionD: "Joyful",
            opcionCorrecta: 2,
            retroalimentacion: " 'Mad' is a synonym of 'angry'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 81),
      ],
      dificultad: 1,
      id: 9,
    ),
    Nivel(
      competencia: 2,
      nivel: 8,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'cactus'?",
            imagenEncabezado: "",
            opcionA: "Cactuses",
            opcionB: "Cacti",
            opcionC: "Cactuses",
            opcionD: "Cactis",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'cactus' is 'cacti'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 82),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a conjunction?",
            imagenEncabezado: "",
            opcionA: "And",
            opcionB: "Quick",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'And' is a conjunction.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 83),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'full'?",
            imagenEncabezado: "",
            opcionA: "Empty",
            opcionB: "Filled",
            opcionC: "Complete",
            opcionD: "Whole",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'full' is 'empty'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 84),
      ],
      dificultad: 1,
      id: 10,
    ),
    Nivel(
      competencia: 2,
      nivel: 9,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'swim'?",
            imagenEncabezado: "",
            opcionA: "Swam",
            opcionB: "Swum",
            opcionC: "Swimming",
            opcionD: "Swims",
            opcionCorrecta: 1,
            retroalimentacion: " The past tense of 'swim' is 'swam'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 85),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adjective?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Beautiful' is an adjective.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 86),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'sad'?",
            imagenEncabezado: "",
            opcionA: "Happy",
            opcionB: "Unhappy",
            opcionC: "Joyful",
            opcionD: "Excited",
            opcionCorrecta: 2,
            retroalimentacion: " 'Unhappy' is a synonym of 'sad'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 87),
      ],
      dificultad: 1,
      id: 11,
    ),
    Nivel(
      competencia: 2,
      nivel: 10,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'leaf'?",
            imagenEncabezado: "",
            opcionA: "Leafs",
            opcionB: "Leaves",
            opcionC: "Leafes",
            opcionD: "Leafs",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'leaf' is 'leaves'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 88),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a verb?",
            imagenEncabezado: "",
            opcionA: "Quick",
            opcionB: "Run",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Run' is a verb.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 89),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'soft'?",
            imagenEncabezado: "",
            opcionA: "Hard",
            opcionB: "Smooth",
            opcionC: "Gentle",
            opcionD: "Tender",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'soft' is 'hard'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 90),
      ],
      dificultad: 1,
      id: 12,
    ),
    Nivel(
      competencia: 2,
      nivel: 11,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'take'?",
            imagenEncabezado: "",
            opcionA: "Took",
            opcionB: "Taken",
            opcionC: "Taking",
            opcionD: "Takes",
            opcionCorrecta: 1,
            retroalimentacion: " The past tense of 'take' is 'took'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 91),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a conjunction?",
            imagenEncabezado: "",
            opcionA: "And",
            opcionB: "Quick",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'And' is a conjunction.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 92),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'angry'?",
            imagenEncabezado: "",
            opcionA: "Happy",
            opcionB: "Mad",
            opcionC: "Excited",
            opcionD: "Joyful",
            opcionCorrecta: 2,
            retroalimentacion: " 'Mad' is a synonym of 'angry'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 93),
      ],
      dificultad: 1,
      id: 13,
    ),
    Nivel(
      competencia: 2,
      nivel: 12,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'person'?",
            imagenEncabezado: "",
            opcionA: "Persons",
            opcionB: "People",
            opcionC: "Persones",
            opcionD: "Peoples",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'person' is 'people'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 94),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adjective?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Beautiful' is an adjective.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 95),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'old'?",
            imagenEncabezado: "",
            opcionA: "Young",
            opcionB: "Ancient",
            opcionC: "Elderly",
            opcionD: "Mature",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'old' is 'young'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 96),
      ],
      dificultad: 1,
      id: 14,
    ),
    Nivel(
      competencia: 2,
      nivel: 13,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'buy'?",
            imagenEncabezado: "",
            opcionA: "Bought",
            opcionB: "Buyed",
            opcionC: "Buying",
            opcionD: "Buys",
            opcionCorrecta: 1,
            retroalimentacion:
                " The past tense of 'buy' is 'bought'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 97),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a noun?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Happiness",
            opcionC: "Running",
            opcionD: "Beautiful",
            opcionCorrecta: 2,
            retroalimentacion: " 'Happiness' is a noun.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 98),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'difficult'?",
            imagenEncabezado: "",
            opcionA: "Easy",
            opcionB: "Hard",
            opcionC: "Simple",
            opcionD: "Clear",
            opcionCorrecta: 2,
            retroalimentacion: " 'Hard' is a synonym of 'difficult'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 99),
      ],
      dificultad: 1,
      id: 14,
    ),
    Nivel(
      competencia: 2,
      nivel: 16,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'city'?",
            imagenEncabezado: "",
            opcionA: "Cities",
            opcionB: "Citys",
            opcionC: "Citi",
            opcionD: "Cites",
            opcionCorrecta: 1,
            retroalimentacion: " The plural of 'city' is 'cities'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 100),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adverb?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Quickly' is an adverb.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 101),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'happy'?",
            imagenEncabezado: "",
            opcionA: "Sad",
            opcionB: "Joyful",
            opcionC: "Excited",
            opcionD: "Angry",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'happy' is 'sad'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 102),
      ],
      dificultad: 1,
      id: 16,
    ),
    Nivel(
      competencia: 2,
      nivel: 15,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'speak'?",
            imagenEncabezado: "",
            opcionA: "Spoke",
            opcionB: "Spoken",
            opcionC: "Speaking",
            opcionD: "Speaks",
            opcionCorrecta: 1,
            retroalimentacion:
                " The past tense of 'speak' is 'spoke'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 103),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a conjunction?",
            imagenEncabezado: "",
            opcionA: "And",
            opcionB: "Quick",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'And' is a conjunction.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 104),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'big'?",
            imagenEncabezado: "",
            opcionA: "Small",
            opcionB: "Large",
            opcionC: "Tiny",
            opcionD: "Little",
            opcionCorrecta: 2,
            retroalimentacion: " 'Large' is a synonym of 'big'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 105),
      ],
      dificultad: 1,
      id: 17,
    ),
    Nivel(
      competencia: 2,
      nivel: 16,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'child'?",
            imagenEncabezado: "",
            opcionA: "Childs",
            opcionB: "Children",
            opcionC: "Childes",
            opcionD: "Childer",
            opcionCorrecta: 2,
            retroalimentacion:
                " The plural of 'child' is 'children'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 106),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adjective?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 2,
            retroalimentacion: " 'Beautiful' is an adjective.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 107),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'new'?",
            imagenEncabezado: "",
            opcionA: "Old",
            opcionB: "Young",
            opcionC: "Fresh",
            opcionD: "Recent",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'new' is 'old'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 108),
      ],
      dificultad: 1,
      id: 18,
    ),
    Nivel(
      competencia: 2,
      nivel: 17,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the past tense of 'give'?",
            imagenEncabezado: "",
            opcionA: "Gave",
            opcionB: "Given",
            opcionC: "Giving",
            opcionD: "Gives",
            opcionCorrecta: 1,
            retroalimentacion: " The past tense of 'give' is 'gave'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 109),
        Pregunta(
            encabezado: "",
            question: "Which of the following is a preposition?",
            imagenEncabezado: "",
            opcionA: "Under",
            opcionB: "Run",
            opcionC: "Beautiful",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Under' is a preposition.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 110),
        Pregunta(
            encabezado: "",
            question: "What is the synonym of 'fast'?",
            imagenEncabezado: "",
            opcionA: "Quick",
            opcionB: "Slow",
            opcionC: "Steady",
            opcionD: "Lazy",
            opcionCorrecta: 1,
            retroalimentacion: " 'Quick' is a synonym of 'fast'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 111),
      ],
      dificultad: 1,
      id: 19,
    ),
    Nivel(
      competencia: 2,
      nivel: 18,
      preguntas: [
        Pregunta(
            encabezado: "",
            question: "What is the plural of 'foot'?",
            imagenEncabezado: "",
            opcionA: "Foots",
            opcionB: "Feet",
            opcionC: "Footes",
            opcionD: "Feets",
            opcionCorrecta: 2,
            retroalimentacion: " The plural of 'foot' is 'feet'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 112),
        Pregunta(
            encabezado: "",
            question: "Which of the following is an adverb?",
            imagenEncabezado: "",
            opcionA: "Quickly",
            opcionB: "Beautiful",
            opcionC: "Run",
            opcionD: "Happiness",
            opcionCorrecta: 1,
            retroalimentacion: " 'Quickly' is an adverb.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 113),
        Pregunta(
            encabezado: "",
            question: "What is the opposite of 'hard'?",
            imagenEncabezado: "",
            opcionA: "Soft",
            opcionB: "Difficult",
            opcionC: "Tough",
            opcionD: "Strong",
            opcionCorrecta: 1,
            retroalimentacion: " The opposite of 'hard' is 'soft'.",
            tipoCompetencia: 3,
            complejidad: 1,
            tipoPregunta: 1,
            id: 114),
      ],
      dificultad: 1,
      id: 20,
    ),
  ];
}
